LAB 3:  LÀM SẠCH DỮ LIỆU CƠ BẢN

1. Thiếu dòng tiêu đề ở  file csv

Vấn đề 1: Tiến hành tải dữ liệu vào chương trình ứng dụng Python và giải quyết vấn đề 
“Missing header in the csv file”

1	Mickéy Mousé	56	70kgs	72	69	71	-	-	-
2	Donald Duck	34	154.89lbs	-	-	-	85	84	76
3	Mini Mouse	16		-	-	-	65	69	72
4	Scrooge McDuck		78kgs	78	79	72	-	-	-
5	Pink Panther	54	198.658lbs	-	-	-	69	75
6	Huey McDuck	52	189lbs	-	-	-	68	75	72
7	Dewey McDuck	19	56kgs	-	-	-	71	78	75
8	Scööpy Doo	32	78kgs	78	76	75	-	-	-

In [1]:
import pandas as pd
import numpy as np

column_names = [
    "Id", "Name", "Age", "Weight", 
    "m0006", "m0612", "m1218", 
    "f0006", "f0612", "f1218"
]

df = pd.read_csv("patient_heart_rate.csv", names=column_names, on_bad_lines='skip')

print("--- 5 dòng dữ liệu đầu tiên sau khi thêm header ---")
print(df.head())

--- 5 dòng dữ liệu đầu tiên sau khi thêm header ---
    Id            Name   Age      Weight m0006 m0612 m1218 f0006 f0612 f1218
0  1.0    Mickéy Mousé  56.0       70kgs    72    69    71     -     -     -
1  2.0     Donald Duck  34.0   154.89lbs     -     -     -    85    84    76
2  3.0      Mini Mouse  16.0         NaN     -     -     -    65    69    72
3  4.0  Scrooge McDuck   NaN       78kgs    78    79    72     -     -     -
4  5.0    Pink Panther  54.0  198.658lbs     -     -     -    69   NaN    75

2. Nhiều biến lưu ở một cột

Vấn đề 2: Xử lý vấn đề một cột lưu hỗn hợp nhiều dữ liệu, ở đây là cột “Name” chứa bao 
gồm “Firstname” và “Lastname”, giải pháp là ta sẽ tách ra làm 2 cột

1	Mickéy Mousé	56	70kgs	72	69	71	-	-	-
2	Donald Duck	34	154.89lbs	-	-	-	85	84	76
3	Mini Mouse	16		-	-	-	65	69	72
4	Scrooge McDuck		78kgs	78	79	72	-	-	-
5	Pink Panther	54	198.658lbs	-	-	-	69	75
6	Huey McDuck	52	189lbs	-	-	-	68	75	72
7	Dewey McDuck	19	56kgs	-	-	-	71	78	75
8	Scööpy Doo	32	78kgs	78	76	75	-	-	-

In [2]:
df[['Firstname', 'Lastname']] = df['Name'].str.split(expand=True)

df = df.drop('Name', axis=1)

# 3. Hiển thị lại DataFrame để kiểm tra kết quả cấu trúc mới
print("--- Dữ liệu sau khi tách cột Name thành Firstname và Lastname ---")
print(df.head())

--- Dữ liệu sau khi tách cột Name thành Firstname và Lastname ---
    Id   Age      Weight m0006 m0612 m1218 f0006 f0612 f1218 Firstname  \
0  1.0  56.0       70kgs    72    69    71     -     -     -    Mickéy
1  2.0  34.0   154.89lbs     -     -     -    85    84    76    Donald
2  3.0  16.0         NaN     -     -     -    65    69    72      Mini
3  4.0   NaN       78kgs    78    79    72     -     -     -   Scrooge
4  5.0  54.0  198.658lbs     -     -     -    69   NaN    75      Pink

  Lastname
0    Mousé
1     Duck
2    Mouse
3   McDuck
4  Panther

3. Dữ liệu cột chứa các giá trị đơn vị không nhất quán

Vấn đề 3: Cột Weight có vấn đề về không thống nhất các đơn vị đo lường trong dữ liệu. 
Ta sẽ chuyển các đơn vị về thành đơn vị chuẩn “kg”

1	Mickéy Mousé	56	70kgs	72	69	71	-	-	-
2	Donald Duck	34	154.89lbs	-	-	-	85	84	76
3	Mini Mouse	16		-	-	-	65	69	72
4	Scrooge McDuck		78kgs	78	79	72	-	-	-
5	Pink Panther	54	198.658lbs	-	-	-	69	75
6	Huey McDuck	52	189lbs	-	-	-	68	75	72
7	Dewey McDuck	19	56kgs	-	-	-	71	78	75
8	Scööpy Doo	32	78kgs	78	76	75	-	-	-

In [3]:
# #Problem 3
# Get the Weight column
weight = df["Weight"]

for i in range(0, len(weight)):
    x = str(weight[i])

    # Incase lbs is part of observation remove it
    if "lbs" in x[-3:]:
        # Remove the lbs from the value
        x = x[:-3]
        # Convert string to float
        float_x = float(x)
        # Covert to kgs and store as int
        y = int(float_x / 2.2)
        # Convert back to string
        y = str(y) + "kgs"
        weight[i] = y

print(df)

      Id   Age Weight m0006 m0612 m1218 f0006 f0612 f1218 Firstname Lastname
0    1.0  56.0  70kgs    72    69    71     -     -     -    Mickéy    Mousé
1    2.0  34.0  70kgs     -     -     -    85    84    76    Donald     Duck
2    3.0  16.0    NaN     -     -     -    65    69    72      Mini    Mouse
3    4.0   NaN  78kgs    78    79    72     -     -     -   Scrooge   McDuck
4    5.0  54.0  90kgs     -     -     -    69   NaN    75      Pink  Panther
5    6.0  52.0  85kgs     -     -     -    68    75    72      Huey   McDuck
6    7.0  19.0  56kgs     -     -     -    71    78    75     Dewey   McDuck
7    8.0  32.0  78kgs    78    76    75     -     -     -    Scööpy      Doo
8    NaN   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN       NaN      NaN
9    NaN   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN       NaN      NaN
10   9.0  52.0  85kgs     -     -     -    68    75    72      Huey   McDuck
11  10.0  12.0  45kgs     -     -     -    92    95    87     Louie   McDuck
12  11.0   NaN  60kgs    78    75    72     -     -     -     Henry      Nam
13  12.0  34.0    NaN    65    67    55     -     -     -    Michel     Long
14  13.0   NaN    NaN     -     -     -    68    72    70      Tana    Ricky
15  15.0  52.0  81kgs     -     -     -    68    75    72       NaN      NaN

C:\Users\US\AppData\Local\Temp\ipykernel_11664\1995442458.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weight[i] = y

4. Dữ liệu có một dòng trống

Vấn đề 4: Vấn đề về xuất hiện dòng dữ liệu rỗng (không có giá trị: NaN). Giải pháp có 
thể đưa ra là xóa bỏ

In [4]:
df.dropna(how="all", inplace=True)
print(df)

      Id   Age Weight m0006 m0612 m1218 f0006 f0612 f1218 Firstname Lastname
0    1.0  56.0  70kgs    72    69    71     -     -     -    Mickéy    Mousé
1    2.0  34.0  70kgs     -     -     -    85    84    76    Donald     Duck
2    3.0  16.0    NaN     -     -     -    65    69    72      Mini    Mouse
3    4.0   NaN  78kgs    78    79    72     -     -     -   Scrooge   McDuck
4    5.0  54.0  90kgs     -     -     -    69   NaN    75      Pink  Panther
5    6.0  52.0  85kgs     -     -     -    68    75    72      Huey   McDuck
6    7.0  19.0  56kgs     -     -     -    71    78    75     Dewey   McDuck
7    8.0  32.0  78kgs    78    76    75     -     -     -    Scööpy      Doo
10   9.0  52.0  85kgs     -     -     -    68    75    72      Huey   McDuck
11  10.0  12.0  45kgs     -     -     -    92    95    87     Louie   McDuck
12  11.0   NaN  60kgs    78    75    72     -     -     -     Henry      Nam
13  12.0  34.0    NaN    65    67    55     -     -     -    Michel     Long
14  13.0   NaN    NaN     -     -     -    68    72    70      Tana    Ricky
15  15.0  52.0  81kgs     -     -     -    68    75    72       NaN      NaN

5. Dữ liệu có các dòng trùng lặp

Vấn đề 5: Có nhiều dòng dữ liệu bị trùng lắp thông tin hoàn toàn[fullname, lastname, 
age, weight,....], giải pháp đưa ra là chỉ giữ lại một dòng dữ liệu, tuy nhiên giải pháp phải 
dựa trên nghiệp vụ của tập dữ liệu và quan sát của người xử lý.

In [5]:
df = df.drop_duplicates(subset=['Firstname','Lastname','Age','Weight'])
print(df)

      Id   Age Weight m0006 m0612 m1218 f0006 f0612 f1218 Firstname Lastname
0    1.0  56.0  70kgs    72    69    71     -     -     -    Mickéy    Mousé
1    2.0  34.0  70kgs     -     -     -    85    84    76    Donald     Duck
2    3.0  16.0    NaN     -     -     -    65    69    72      Mini    Mouse
3    4.0   NaN  78kgs    78    79    72     -     -     -   Scrooge   McDuck
4    5.0  54.0  90kgs     -     -     -    69   NaN    75      Pink  Panther
5    6.0  52.0  85kgs     -     -     -    68    75    72      Huey   McDuck
6    7.0  19.0  56kgs     -     -     -    71    78    75     Dewey   McDuck
7    8.0  32.0  78kgs    78    76    75     -     -     -    Scööpy      Doo
11  10.0  12.0  45kgs     -     -     -    92    95    87     Louie   McDuck
12  11.0   NaN  60kgs    78    75    72     -     -     -     Henry      Nam
13  12.0  34.0    NaN    65    67    55     -     -     -    Michel     Long
14  13.0   NaN    NaN     -     -     -    68    72    70      Tana    Ricky
15  15.0  52.0  81kgs     -     -     -    68    75    72       NaN      NaN

6. Các ký tự không phải ASCII

Vấn đề 6: Xuất hiện dữ liệu bị ảnh hưởng bởi lỗi non-ASCII, không định dạng ASCII. 
Giải pháp: Tùy vào nghiệp vụ ta có thể: xóa dữ liệu tại đó, thay thế bằng dữ liệu khác 
hoặc thay bằng việc đánh dấu bằng một kí tự khác (ví dụ: ‘warning’)

In [6]:
df.Firstname.replace({r'[^\x00-\x7F]+':''}, regex=True, inplace=True)
df.Lastname.replace({r'[^\x00-\x7F]+':''}, regex=True, inplace=True)
print(df)

      Id   Age Weight m0006 m0612 m1218 f0006 f0612 f1218 Firstname Lastname
0    1.0  56.0  70kgs    72    69    71     -     -     -     Micky     Mous
1    2.0  34.0  70kgs     -     -     -    85    84    76    Donald     Duck
2    3.0  16.0    NaN     -     -     -    65    69    72      Mini    Mouse
3    4.0   NaN  78kgs    78    79    72     -     -     -   Scrooge   McDuck
4    5.0  54.0  90kgs     -     -     -    69   NaN    75      Pink  Panther
5    6.0  52.0  85kgs     -     -     -    68    75    72      Huey   McDuck
6    7.0  19.0  56kgs     -     -     -    71    78    75     Dewey   McDuck
7    8.0  32.0  78kgs    78    76    75     -     -     -      Scpy      Doo
11  10.0  12.0  45kgs     -     -     -    92    95    87     Louie   McDuck
12  11.0   NaN  60kgs    78    75    72     -     -     -     Henry      Nam
13  12.0  34.0    NaN    65    67    55     -     -     -    Michel     Long
14  13.0   NaN    NaN     -     -     -    68    72    70      Tana    Ricky
15  15.0  52.0  81kgs     -     -     -    68    75    72       NaN      NaN

7. Giá trị bị mất

Vấn đề 7: “Missing values”, vấn đề này xảy ra tại các cột “Age”, “Weight” và “Heart 
Rate”. Thiếu dữ liệu (dữ liệu không đầy đủ) là vấn đề xảy ra nhiều trong các nguồn dữ 
liệu do nhiều nguyên nhân chủ quan lẫn khách quan.Có một vài giải pháp để xử lý vấn đề 
này, chủ yếu dựa trên kinh nghiệm và nghiệp vụ về tập dữ liệu đó. Một số giải pháp đưa 
đề xuất từ chuyên gia như sau: 
a. Deletion: Remove records with missing values 
b. Dummy substitution: Replace missing values with a dummy but valid value: 
e.g.: 0 for numerical values. 
c. Mean substitution: Replace the missing values with the mean. 
d. Frequent substitution: Replace the missing values with the most frequent item. 
e. Improve the data collector: Your business folk will talk to the clients and inform 
them about why it is worth fixing the problem with the data collector. 
……

a. Deletion: Remove records with missing values

In [7]:
df_a = df.copy()

df_a.dropna(subset=["Age", "Weight"], how="any", inplace=True)

print("--- Kết quả sau khi XÓA các dòng bị khuyết ---")
df_a

--- Kết quả sau khi XÓA các dòng bị khuyết ---

      Id   Age Weight m0006 m0612 m1218 f0006 f0612 f1218 Firstname Lastname
0    1.0  56.0  70kgs    72    69    71     -     -     -     Micky     Mous
1    2.0  34.0  70kgs     -     -     -    85    84    76    Donald     Duck
4    5.0  54.0  90kgs     -     -     -    69   NaN    75      Pink  Panther
5    6.0  52.0  85kgs     -     -     -    68    75    72      Huey   McDuck
6    7.0  19.0  56kgs     -     -     -    71    78    75     Dewey   McDuck
7    8.0  32.0  78kgs    78    76    75     -     -     -      Scpy      Doo
11  10.0  12.0  45kgs     -     -     -    92    95    87     Louie   McDuck
15  15.0  52.0  81kgs     -     -     -    68    75    72       NaN      NaN

b. Dummy substitution: Replace missing values with a dummy but valid value: 
e.g.: 0 for numerical values.

In [8]:
# Tạo bản sao để thử nghiệm phương pháp b
df_b = df.copy()

df_b["Age"] = df_b["Age"].fillna(0)
df_b["Weight"] = df_b["Weight"].fillna(0)

print("--- Kết quả sau khi thay thế giá trị khuyết bằng số 0 ---")
df_b

--- Kết quả sau khi thay thế giá trị khuyết bằng số 0 ---

      Id   Age Weight m0006 m0612 m1218 f0006 f0612 f1218 Firstname Lastname
0    1.0  56.0  70kgs    72    69    71     -     -     -     Micky     Mous
1    2.0  34.0  70kgs     -     -     -    85    84    76    Donald     Duck
2    3.0  16.0      0     -     -     -    65    69    72      Mini    Mouse
3    4.0   0.0  78kgs    78    79    72     -     -     -   Scrooge   McDuck
4    5.0  54.0  90kgs     -     -     -    69   NaN    75      Pink  Panther
5    6.0  52.0  85kgs     -     -     -    68    75    72      Huey   McDuck
6    7.0  19.0  56kgs     -     -     -    71    78    75     Dewey   McDuck
7    8.0  32.0  78kgs    78    76    75     -     -     -      Scpy      Doo
11  10.0  12.0  45kgs     -     -     -    92    95    87     Louie   McDuck
12  11.0   0.0  60kgs    78    75    72     -     -     -     Henry      Nam
13  12.0  34.0      0    65    67    55     -     -     -    Michel     Long
14  13.0   0.0      0     -     -     -    68    72    70      Tana    Ricky
15  15.0  52.0  81kgs     -     -     -    68    75    72       NaN      NaN

c. Mean substitution: Replace the missing values with the mean.

In [9]:
df_c = df.copy()

if df_c["Weight"].dtype == "object":
    df_c["Weight"] = df_c["Weight"].str.replace("kgs", "").astype(float)

mean_age = df_c["Age"].mean()
mean_weight = df_c["Weight"].mean()

# Điền giá trị trung bình vào các ô trống (làm tròn để số đẹp hơn)
df_c["Age"] = df_c["Age"].fillna(round(mean_age, 1))
df_c["Weight"] = df_c["Weight"].fillna(round(mean_weight, 1))

print("--- Kết quả sau khi thay thế bằng giá trị TRUNG BÌNH ---")
df_c

--- Kết quả sau khi thay thế bằng giá trị TRUNG BÌNH ---

      Id   Age  Weight m0006 m0612 m1218 f0006 f0612 f1218 Firstname Lastname
0    1.0  56.0    70.0    72    69    71     -     -     -     Micky     Mous
1    2.0  34.0    70.0     -     -     -    85    84    76    Donald     Duck
2    3.0  16.0    71.3     -     -     -    65    69    72      Mini    Mouse
3    4.0  36.1    78.0    78    79    72     -     -     -   Scrooge   McDuck
4    5.0  54.0    90.0     -     -     -    69   NaN    75      Pink  Panther
5    6.0  52.0    85.0     -     -     -    68    75    72      Huey   McDuck
6    7.0  19.0    56.0     -     -     -    71    78    75     Dewey   McDuck
7    8.0  32.0    78.0    78    76    75     -     -     -      Scpy      Doo
11  10.0  12.0    45.0     -     -     -    92    95    87     Louie   McDuck
12  11.0  36.1    60.0    78    75    72     -     -     -     Henry      Nam
13  12.0  34.0    71.3    65    67    55     -     -     -    Michel     Long
14  13.0  36.1    71.3     -     -     -    68    72    70      Tana    Ricky
15  15.0  52.0    81.0     -     -     -    68    75    72       NaN      NaN

d. Frequent substitution: Replace the missing values with the most frequent item.

In [10]:
# Tạo bản sao để thử nghiệm phương pháp d
df_d = df.copy()

mode_age = df_d["Age"].mode()[0]
mode_weight = df_d["Weight"].mode()[0]

# Điền giá trị xuất hiện nhiều nhất vào các ô trống
df_d["Age"] = df_d["Age"].fillna(mode_age)
df_d["Weight"] = df_d["Weight"].fillna(mode_weight)

print("--- Kết quả sau khi thay thế bằng giá trị XUẤT HIỆN NHIỀU NHẤT ---")
df_d

--- Kết quả sau khi thay thế bằng giá trị XUẤT HIỆN NHIỀU NHẤT ---

      Id   Age Weight m0006 m0612 m1218 f0006 f0612 f1218 Firstname Lastname
0    1.0  56.0  70kgs    72    69    71     -     -     -     Micky     Mous
1    2.0  34.0  70kgs     -     -     -    85    84    76    Donald     Duck
2    3.0  16.0  70kgs     -     -     -    65    69    72      Mini    Mouse
3    4.0  34.0  78kgs    78    79    72     -     -     -   Scrooge   McDuck
4    5.0  54.0  90kgs     -     -     -    69   NaN    75      Pink  Panther
5    6.0  52.0  85kgs     -     -     -    68    75    72      Huey   McDuck
6    7.0  19.0  56kgs     -     -     -    71    78    75     Dewey   McDuck
7    8.0  32.0  78kgs    78    76    75     -     -     -      Scpy      Doo
11  10.0  12.0  45kgs     -     -     -    92    95    87     Louie   McDuck
12  11.0  34.0  60kgs    78    75    72     -     -     -     Henry      Nam
13  12.0  34.0  70kgs    65    67    55     -     -     -    Michel     Long
14  13.0  34.0  70kgs     -     -     -    68    72    70      Tana    Ricky
15  15.0  52.0  81kgs     -     -     -    68    75    72       NaN      NaN

e. Improve the data collector: Your business folk will talk to the clients and inform 
them about why it is worth fixing the problem with the data collector.

In [18]:
# Tạo bản sao để thử nghiệm phương pháp d
df_d = df.copy()

mode_age = df_d["Age"].mode()[0]
mode_weight = df_d["Weight"].mode()[0]

df_d["Age"] = df_d["Age"].fillna(mode_age)
df_d["Weight"] = df_d["Weight"].fillna(mode_weight)

print("--- Kết quả sau khi thay thế bằng giá trị XUẤT HIỆN NHIỀU NHẤT ---")
df_d

--- Kết quả sau khi thay thế bằng giá trị XUẤT HIỆN NHIỀU NHẤT ---

       Id   Age Weight Firstname Lastname PulseRate  Sex Time
0     1.0  56.0  70kgs     Micky     Mous        72  NaN  NaN
1     1.0  56.0  70kgs     Micky     Mous        69  NaN  NaN
2     1.0  56.0  70kgs     Micky     Mous        71  NaN  NaN
3     1.0  56.0  70kgs     Micky     Mous        70  NaN  NaN
4     1.0  56.0  70kgs     Micky     Mous        70  NaN  NaN
..    ...   ...    ...       ...      ...       ...  ...  ...
697  15.0  52.0  81kgs       NaN      NaN       NaN  NaN  NaN
698  15.0  52.0  81kgs       NaN      NaN       NaN  NaN  NaN
699  15.0  52.0  81kgs       NaN      NaN       NaN  NaN  NaN
700  15.0  52.0  81kgs       NaN      NaN       NaN  NaN  NaN
701  15.0  52.0  81kgs       NaN      NaN       NaN  NaN  NaN

[702 rows x 8 columns]

 Vấn đề 8: “một cột chứa quá nhiều thông tin cần được phân rã”, như trong bài toán này ta 
thấy header “m0006” chứa các nội dung bao gồm: m → male, 1218 ~ 12-18 (mm-dd). 
Còn giá trị thì là kết quả huyết áp.

In [19]:
import numpy as np
import pandas as pd

# 1. ĐỌC LẠI FILE VÀ ĐỒNG BỘ NHANH (Bắt buộc để reset dữ liệu trong bộ nhớ Jupyter, tránh lỗi chạy lại bị NaN)
column_names = [
    "Id",
    "Name",
    "Age",
    "Weight",
    "m0006",
    "m0612",
    "m1218",
    "f0006",
    "f0612",
    "f1218",
]
df = pd.read_csv("patient_heart_rate.csv", names=column_names, on_bad_lines="skip")
df.dropna(how="all", inplace=True)

# Đồng bộ lại các bước tiền xử lý trước đó
df[["Firstname", "Lastname"]] = df["Name"].astype(str).str.split(expand=True)
df = df.drop("Name", axis=1)

for i in range(0, len(df["Weight"])):
    x = str(df["Weight"].iloc[i])
    if "lbs" in x:
        df.at[df.index[i], "Weight"] = str(int(float(x[:-3]) / 2.2)) + "kgs"


# 2. TIẾN HÀNH MELT BẢNG DỮ LIỆU
df = pd.melt(
    df,
    id_vars=["Id", "Age", "Weight", "Firstname", "Lastname"],
    value_name="PulseRate",
    var_name="sex_and_time",
)

# Sắp xếp để gom nhóm dữ liệu theo từng người cho giống ảnh mẫu
df = df.sort_values(by=["Id", "Age", "Weight", "Firstname", "Lastname"])


# 3. SỬ DỤNG REGEX ĐỂ TRÍCH XUẤT CÁC THÔNG TIN
# ^(\D): Lấy ký tự chữ đầu tiên (m hoặc f)
# (\d{2})(\d{2}): Tách 4 chữ số phía sau thành 2 nhóm giờ
extract_df = df["sex_and_time"].str.extract(r"^(\D)(\d{2})(\d{2})")
extract_df.columns = ["Sex", "hours_lower", "hours_upper"]
extract_df.index = df.index  # Đồng bộ chỉ số hàng để tuyệt đối không bị lỗi NaN khi gán


# 4. GÁN DỮ LIỆU VÀ CHUYỂN ĐỔI THÀNH CHỮ 'M' / 'F' IN HOA
df["Sex"] = extract_df["Sex"].str.upper()  # .upper() sẽ biến 'm'->'M' và 'f'->'F'
df["Time"] = extract_df["hours_lower"] + "-" + extract_df["hours_upper"]


# 5. DỌN DẸP BẢNG DỮ LIỆU
df = df.drop("sex_and_time", axis=1)
df["PulseRate"] = df["PulseRate"].replace("-", np.nan)

# Sắp xếp lại thứ tự các cột chuẩn theo yêu cầu của bạn
ordered_cols = [
    "Id",
    "Age",
    "Weight",
    "Firstname",
    "Lastname",
    "PulseRate",
    "Sex",
    "Time",
]
df = df[ordered_cols]

print("--- Bảng dữ liệu sạch chuẩn cho Vấn đề 8 (Cột Sex dạng M/F) ---")
df

--- Bảng dữ liệu sạch chuẩn cho Vấn đề 8 (Cột Sex dạng M/F) ---

      Id   Age Weight Firstname Lastname PulseRate Sex   Time
0    1.0  56.0  70kgs    Mickéy    Mousé        72   M  00-06
14   1.0  56.0  70kgs    Mickéy    Mousé        69   M  06-12
28   1.0  56.0  70kgs    Mickéy    Mousé        71   M  12-18
42   1.0  56.0  70kgs    Mickéy    Mousé       NaN   F  00-06
56   1.0  56.0  70kgs    Mickéy    Mousé       NaN   F  06-12
..   ...   ...    ...       ...      ...       ...  ..    ...
27  15.0  52.0  81kgs       nan     None       NaN   M  06-12
41  15.0  52.0  81kgs       nan     None       NaN   M  12-18
55  15.0  52.0  81kgs       nan     None        68   F  00-06
69  15.0  52.0  81kgs       nan     None        75   F  06-12
83  15.0  52.0  81kgs       nan     None        72   F  12-18

[84 rows x 8 columns]

11. Hãy khảo sát tỉ lệ dữ liệu thiếu trên biến huyết áp. Dữ liệu bị thiếu thì hãy xử lý bằng 
phương pháp sau 
• Thay thế bằng giá trị trung bình liền trước và liền sau của người đó. Nếu không 
được thì dùng 2) 
• Thay thế bằng giá trị trung bình 2 giá liền trước của người đó. Nếu không được 
thì dùng 3) 
• Thay thế bằng giá trị trung bình 2 giá liền sau của người đó. Nếu không được thì 
dùng 4) 
• Trung bình của các giá trị huyết áp của người đó. Nếu không được thì dùng 5). 
• Trung bình của các giá trị huyết áp của nhóm giới tính. Nếu không được thì dùng 
6) 
• Trung bình của các
giá trị dữ liệu. Nếu không được thì thay bằng mức ổn định 
trong y học.

In [20]:

df["PulseRate"] = pd.to_numeric(df["PulseRate"].replace("-", np.nan), errors="coerce")

# 1. Khảo sát tỉ lệ dữ liệu thiếu sau khi đồng bộ
missing_ratio = df["PulseRate"].isna().mean() * 100
print(f"Tỉ lệ dữ liệu khuyết trên cột PulseRate: {missing_ratio:.2f}%\n")


# 2. Định nghĩa hàm xử lý nội suy y tế theo các tầng điều kiện từ chuyên gia
def fill_pulse_rate(group):
    # Lấy mảng giá trị của người đó
    pulse = group["PulseRate"].copy()

    # Tầng 1: Trung bình của liền trước và liền sau
    t1 = (pulse.shift(1) + pulse.shift(-1)) / 2
    pulse = pulse.fillna(t1)

    # Tầng 2: Trung bình của 2 giá trị liền trước
    t2 = (pulse.shift(1) + pulse.shift(2)) / 2
    pulse = pulse.fillna(t2)

    # Tầng 3: Trung bình của 2 giá trị liền sau
    t3 = (pulse.shift(-1) + pulse.shift(-2)) / 2
    pulse = pulse.fillna(t3)

    # Tầng 4: Trung bình của các giá trị hiện có của chính người đó
    t4 = pulse.mean()
    pulse = pulse.fillna(t4)

    group["PulseRate"] = pulse
    return group


# Áp dụng 4 tầng đầu tiên cho từng cá nhân (group theo Id)
df = df.groupby("Id", group_keys=False).apply(fill_pulse_rate)

# Tầng 5: Nếu vẫn khuyết, thay bằng trung bình của nhóm giới tính (Sex)
df["PulseRate"] = df.groupby("Sex")["PulseRate"].transform(
    lambda x: x.fillna(x.mean())
)

# Tầng 6: Nếu vẫn khuyết, thay bằng mức ổn định mặc định trong y học (70 bpm)
df["PulseRate"] = df["PulseRate"].fillna(70)

# Làm tròn chỉ số huyết áp về số nguyên cho sạch đẹp
df["PulseRate"] = df["PulseRate"].round().astype(int)

print("--- Hoàn thành xử lý nội suy khuyết dữ liệu PulseRate ---")
df.head(10)

Tỉ lệ dữ liệu khuyết trên cột PulseRate: 51.19%

--- Hoàn thành xử lý nội suy khuyết dữ liệu PulseRate ---

     Id   Age Weight Firstname Lastname  PulseRate Sex   Time
0   1.0  56.0  70kgs    Mickéy    Mousé         72   M  00-06
14  1.0  56.0  70kgs    Mickéy    Mousé         69   M  06-12
28  1.0  56.0  70kgs    Mickéy    Mousé         71   M  12-18
42  1.0  56.0  70kgs    Mickéy    Mousé         70   F  00-06
56  1.0  56.0  70kgs    Mickéy    Mousé         70   F  06-12
70  1.0  56.0  70kgs    Mickéy    Mousé         70   F  12-18
1   2.0  34.0  70kgs    Donald     Duck         82   M  00-06
15  2.0  34.0  70kgs    Donald     Duck         82   M  06-12
29  2.0  34.0  70kgs    Donald     Duck         84   M  12-18
43  2.0  34.0  70kgs    Donald     Duck         85   F  00-06

12. Hãy rút gọn dữ liệu phù hợp và reindex lại dữ liệu. Sau đó, lưu trữ dữ liệu đã xử lý thành 
công với tên file patient_heart_rate_clean.csv

In [22]:
# --- Câu 12: Rút gọn cấu trúc cột, Reindex và lưu file ---

# Đắp lại thứ tự cột theo đúng ảnh mẫu hiển thị
ordered_columns = [
    "Id",
    "Age",
    "Weight",
    "Firstname",
    "Lastname",
    "PulseRate",
    "Sex",
    "Time",
]
df_clean = df[ordered_columns]

# Tiến hành làm sạch index (bắt đầu lại từ 0, không giữ vết index cũ bị xáo trộn)
df_clean = df_clean.reset_index(drop=True)

# Lưu trữ dữ liệu sạch ra file theo đúng tên yêu cầu
df_clean.to_csv("patient_heart_rate_clean.csv", index=False)

print("--- KẾT QUẢ DỮ LIỆU SẠCH CUỐI CÙNG ---")
df_clean

--- KẾT QUẢ DỮ LIỆU SẠCH CUỐI CÙNG ---

      Id   Age Weight Firstname Lastname  PulseRate Sex   Time
0    1.0  56.0  70kgs    Mickéy    Mousé         72   M  00-06
1    1.0  56.0  70kgs    Mickéy    Mousé         69   M  06-12
2    1.0  56.0  70kgs    Mickéy    Mousé         71   M  12-18
3    1.0  56.0  70kgs    Mickéy    Mousé         70   F  00-06
4    1.0  56.0  70kgs    Mickéy    Mousé         70   F  06-12
..   ...   ...    ...       ...      ...        ...  ..    ...
79  15.0  52.0  81kgs       nan     None         72   M  06-12
80  15.0  52.0  81kgs       nan     None         72   M  12-18
81  15.0  52.0  81kgs       nan     None         68   F  00-06
82  15.0  52.0  81kgs       nan     None         75   F  06-12
83  15.0  52.0  81kgs       nan     None         72   F  12-18

[84 rows x 8 columns]